<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?= '首页'?></title>
    <?php include  APP_PATH . '/application/modules/Backend/views/common/head.phtml'?>
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">


    <?php include  APP_PATH . '/application/modules/Backend/views/common/nav.phtml'?>

    <?php include  APP_PATH . '/application/modules/Backend/views/common/sidebar.phtml'?>


    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <small></small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
                    <li class="active">Here</li>
                </ol>
        </section>

        <!-- Main content -->
        <section class="content">

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    <?php include  APP_PATH . '/application/modules/Backend/views/common/footer.phtml'?>


    <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->
    <?php include APP_PATH . '/application/modules/Backend/views/common/script.phtml'?>

</body>
</html>
