<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>SungLife Login</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/sunglife_b.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/libs/AdminLTE/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link rel="stylesheet" href="/libs/AdminLTE/dist/css/skins/skin-blue.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="/js/html5shiv.min.js"></script>
    <script src="/js/respond.min.js"></script>
    <![endif]-->


</head>

<body class="hold-transition login-bg">
<div class="login-box">
    <div class="login-logo">
        <a href="/manage/admin/login"><b>S&L后台管理登录</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">Study Laravel后台管理</p>

        <form action="" method="" class="login-form">
            <div class="form-group has-feedback">
                <input type="text" class="form-control"  name="username" value="" placeholder="账号">
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" class="form-control" name="password" value="" placeholder="密码">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <div class="row">
                    <div class="col-sm-6">
                        <input type="checkbox" name="remember_me" > 记住密码
                    </div>

                    <!-- /.col -->
                    <div class="col-sm-6 text-right">
                        <button type="button" class="btn btn-primary btn-block btn-flat btn-login">登录</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
    <!-- /.login-box-body -->
</div>

<!-- jQuery 2.2.3 -->
<script src="/js/jquery.min.js"></script>
<script src="/libs/AdminLTE/plugins/iCheck/icheck.min.js"></script>
<script src="/libs/layer/layer.js"></script>
<!-- Bootstrap 3.3.6 -->
</body>
</html>

<script type="text/javascript">
    $(function() {
        // #1 按Enter 键 登录
        $("body").bind('keydown', function(){
            if(event.keyCode == 13){
                $(".btn-login").click();
            }
        });

        $(".btn-login").bind('click', function() {
            var formData = $(".login-form").serialize();
            $.ajax({
                url     : '#',
                type    : 'POST',
                dataType: 'json',
                data    : formData,
                success : function(res) {
                    if(res.status == 0){
                        layer.msg(res.msg, {icon: 1, time: 1000}, function() {
                            window.location.href=res.data.redirectUrl;
                        });
                    }else {
                        layer.msg(res.msg, {icon: 0});
                    }
                }
            });
        });

    });
</script>

