<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <?php include APP_PATH . "/application/views/common/header.phtml" ?>
        <title>Sunglife</title>
        <meta name="keywords" content="">
        <meta name="description" content="">
    </head>
    <body class="body-bg">
        <?php include APP_PATH . "/application/views/common/nav.phtml"?>
        <div class="container">
            <div class="row">
                <div class="col-sm-9 " >
                    <div class="well">
                        <div class="row ">
                            <div class="col-md-4">
                                <a href="#" >
                                    <img src="/img/home/expo.png"  class="img-responsive center-block"  alt="">
                                </a>
                            </div>
                            <div class="col-md-8">panel body</div>
                        </div>

                    </div>
                    <div class="well ">
                        <div class="row ">
                            <div class="col-md-4">
                                <a href="#" >
                                    <img src="/img/home/expo.png"  class="img-responsive center-block"  alt="">
                                </a>
                            </div>
                            <div class="col-md-8">panel body</div>
                        </div>

                    </div>
                    <div class="well ">
                        <div class="row ">
                            <div class="col-md-4">
                                <a href="#" >
                                    <img src="/img/home/expo.png"  class="img-responsive center-block"  alt="">
                                </a>
                            </div>
                            <div class="col-md-8">panel body</div>
                        </div>

                    </div>
                    <div >
                        <nav aria-label="">
                            <ul class="pager">
                                <li class="previous disabled"><a href="#"><span aria-hidden="true">&larr;</span> Older</a></li>
                                <li class="next"><a href="#">Newer <span aria-hidden="true">&rarr;</span></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>

                <div class="col-sm-3 ">
                    <div class="panel panel-success">
                        <div class="panel-heading well-sm">
                            <h3 class="panel-title">Panel title</h3>
                        </div>
                        <div class="panel-body well-sm">
                            Panel content
                            Panel content
                            Panel content
                        </div>
                    </div>
                    <div class="panel panel-success">
                        <div class="panel-heading well-sm">
                            <h3 class="panel-title">Panel title</h3>
                        </div>
                        <div class="panel-body well-sm">
                            Panel content
                            Panel content
                            Panel content
                        </div>
                    </div>
                    <div class="panel panel-success">
                        <div class="panel-heading well-sm">
                            <h3 class="panel-title">Panel title</h3>
                        </div>
                        <div class="panel-body well-sm">
                            Panel content
                            Panel content
                            Panel content
                        </div>
                    </div>

                </div>
            </div>
        </div>


        <?php include APP_PATH . "/application/views/common/footer.phtml"?>
    </body>
</html>